import { Inter } from 'next/font/google'
import Navtabs from './Navtabs'
const inter = Inter({ subsets: ['latin'] })

export const metadatas = {
    title: 'Codedamn Profile',
    description: 'Generated by create next app',
}

const layout = ({ children }) => {

    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="grid grid-cols-5 gap-16 m-11">
                    <Navtabs/>
                    <div className="xl:col-span-4">
                        <div className="mb-4">{children}</div>
                    </div>
                </div>
            </body>
        </html>
    )
}

export default layout;